runmode: PRODUCTION
github-discussion:
  owner: kgca-development
  repository: killarney-development
neighborhood:
  name: Killarney
  bounding-box:
    north-latitude: 51.038912
    east-longitude: -114.117927
    south-latitude: 51.022361
    west-longitude: -114.142638
